<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsAnalyzer>true</IsAnalyzer>
    <DevelopmentDependency>true</DevelopmentDependency>
    <PackageId>Abaddax.Roslyn.Analyzers</PackageId>
    <PackageTags>Abaddax.Roslyn.Analyzers, analyzers</PackageTags>
    <Version>0.0.1-preview7</Version>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
  </PropertyGroup>

  <PropertyGroup>
    <!--<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>--> 
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_AddAnalyzersToOutput</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abaddax.Roslyn.Analyzers.CodeFixes\Abaddax.Roslyn.Analyzers.CodeFixes.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>CodefixesOutput</OutputItemType>   
    </ProjectReference>
    <ProjectReference Include="..\Abaddax.Roslyn.Analyzers\Abaddax.Roslyn.Analyzers.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>AnalyzersOutput</OutputItemType>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="build/**" Pack="true" PackagePath="build/" />
    <None Include="buildMultiTargeting/**" Pack="true" PackagePath="buildMultiTargeting/" />
  </ItemGroup>

  <Target Name="ResigsterAnalyzersOutputForClean"
          AfterTargets="ResolveReferences"
          BeforeTargets="IncrementalClean">
    <ItemGroup>
      <FileWrites Include="@(AnalyzersOutput->'$(OutputPath)%(Filename)%(Extension)')" />
      <FileWrites Include="@(CodefixesOutput->'$(OutputPath)%(Filename)%(Extension)')" />
    </ItemGroup>
  </Target>
  <Target Name="CopyAnalyzersToOutput"
          AfterTargets="Build">
    <Copy SourceFiles="@(AnalyzersOutput)"
          DestinationFolder="$(OutputPath)"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(CodefixesOutput)"
          DestinationFolder="$(OutputPath)"
          SkipUnchangedFiles="true" />
  </Target>

  <Target Name="_AddAnalyzersToOutput"
          AfterTargets="Build"
          BeforeTargets="Pack">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(OutputPath)\Abaddax.Roslyn.Analyzers.dll" PackagePath="analyzers/dotnet/cs" />
      <TfmSpecificPackageFile Include="$(OutputPath)\Abaddax.Roslyn.Analyzers.CodeFixes.dll" PackagePath="analyzers/dotnet/cs" />
    </ItemGroup>
  </Target>

</Project>
